version: "3"
services:
  opentest_server:
    image: opentest:server
    restart: unless-stopped
    container_name: "opentest_server"
    hostname: "opentest_server"
    ports:
      - "3001:3001"
    volumes:
      - ./opentest:/opt/opentest

  opentest_actor1:
    image: opentest:actor
    restart: unless-stopped
    container_name: "opentest_actor1"
    hostname: "opentest_actor1"
    volumes:
      - ./opentest/actor:/opt/opentest/actor1
    depends_on:
      - opentest_server

  selenium-hub:
    image: selenium-hub:4.8.1-20230306
    restart: unless-stopped
    container_name: selenium-hub
    hostname: "selenium_hub"
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"

  chrome:
    image: selenium-node-chrome:4.8.1-20230306
    restart: unless-stopped
    shm_size: 2gb
    container_name: selenium_chrome
    hostname: "selenium_chrome"
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  chrome_video:
    image: selenium-video:ffmpeg-4.3.1-20230306
    restart: unless-stopped
    container_name: selenium_chrome_video
    hostname: "selenium_chrome_video"
    volumes:
      - ./selenium/videos:/videos
      - ./selenium/configs/supervisord.conf:/etc/supervisord.conf
    depends_on:
      - chrome
    environment:
      - DISPLAY_CONTAINER_NAME=chrome
      - FILE_NAME=chrome_video.mp4
